services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.5.3
    hostname: zookeeper1
    container_name: zookeeper1
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: 0.0.0.0:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888;zookeeper4:2888:3888;zookeeper5:2888:3888
  zookeeper2:
    image: confluentinc/cp-zookeeper:7.5.3
    hostname: zookeeper2
    container_name: zookeeper2
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;0.0.0.0:2888:3888;zookeeper3:2888:3888;zookeeper4:2888:3888;zookeeper5:2888:3888
  zookeeper3:
    image: confluentinc/cp-zookeeper:7.5.3
    hostname: zookeeper3
    container_name: zookeeper3
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;0.0.0.0:2888:3888;zookeeper4:2888:3888;zookeeper5:2888:3888
  zookeeper4:
    image: confluentinc/cp-zookeeper:7.5.3
    hostname: zookeeper4
    container_name: zookeeper4
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 4
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888;0.0.0.0:2888:3888;zookeeper5:2888:3888
  zookeeper5:
    image: confluentinc/cp-zookeeper:7.5.3
    hostname: zookeeper5
    container_name: zookeeper5
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 5
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888;zookeeper4:2888:3888;0.0.0.0:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:7.5.3
    hostname: kafka1
    container_name: kafka1
    restart: unless-stopped
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - zookeeper4
      - zookeeper5
    ports:
      - "9091:9091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: rack1
      CLUSTER_ID: kafka-cluster
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1:2181,zookeeper2:2181,zookeeper3:2181,zookeeper4:2181,zookeeper5:2181'
      KAFKA_ADVERTISED_LISTENERS: CLUSTER://kafka1:29091,CLIENT://127.0.0.1:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLUSTER:PLAINTEXT,CLIENT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: CLUSTER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  kafka2:
    image: confluentinc/cp-kafka:7.5.3
    hostname: kafka2
    container_name: kafka2
    restart: unless-stopped
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - zookeeper4
      - zookeeper5
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_BROKER_RACK: rack2
      CLUSTER_ID: kafka-cluster
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1:2181,zookeeper2:2181,zookeeper3:2181,zookeeper4:2181,zookeeper5:2181'
      KAFKA_LISTENERS: CLUSTER://:29092,CLIENT://:9092
      KAFKA_ADVERTISED_LISTENERS: CLUSTER://kafka2:29092,CLIENT://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLUSTER:PLAINTEXT,CLIENT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: CLUSTER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka3:
    image: confluentinc/cp-kafka:7.5.3
    hostname: kafka3
    container_name: kafka3
    restart: unless-stopped
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - zookeeper4
      - zookeeper5
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_BROKER_RACK: rack3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1:2181,zookeeper2:2181,zookeeper3:2181,zookeeper4:2181,zookeeper5:2181'
      KAFKA_LISTENERS: CLUSTER://:29093,CLIENT://:9093
      KAFKA_ADVERTISED_LISTENERS: CLUSTER://kafka3:29093,CLIENT://127.0.0.1:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLUSTER:PLAINTEXT,CLIENT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: CLUSTER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  kafka4:
    image: confluentinc/cp-kafka:7.5.3
    hostname: kafka4
    container_name: kafka4
    restart: unless-stopped
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - zookeeper4
      - zookeeper5
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 4
      KAFKA_BROKER_RACK: rack4
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1:2181,zookeeper2:2181,zookeeper3:2181,zookeeper4:2181,zookeeper5:2181'
      KAFKA_LISTENERS: CLUSTER://:29094,CLIENT://:9094
      KAFKA_ADVERTISED_LISTENERS: CLUSTER://kafka4:29094,CLIENT://127.0.0.1:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLUSTER:PLAINTEXT,CLIENT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: CLUSTER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka5:
    image: confluentinc/cp-kafka:7.5.3
    hostname: kafka5
    container_name: kafka5
    restart: unless-stopped
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - zookeeper4
      - zookeeper5
    ports:
      - "9095:9095"
    environment:
      KAFKA_BROKER_ID: 5
      KAFKA_BROKER_RACK: rack5
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1:2181,zookeeper2:2181,zookeeper3:2181,zookeeper4:2181,zookeeper5:2181'
      KAFKA_LISTENERS: CLUSTER://:29095,CLIENT://:9095
      KAFKA_ADVERTISED_LISTENERS: CLUSTER://kafka5:29095,CLIENT://127.0.0.1:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLUSTER:PLAINTEXT,CLIENT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: CLUSTER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-console:
    image: redpandadata/console:v2.6.1
    restart: unless-stopped
    container_name: kafka-console
    ports:
      - "9000:8080"
    environment:
      KAFKA_BROKERS: kafka1:29091,kafka2:29092,kafka3:29093,kafka4:29094,kafka5:29095
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - kafka4
      - kafka5

